version: "3"

services:
  api-server-db:
    image: mongo
    ports:
      - 27017:27017
    container_name: api-server-db

  api-server:
    build: .
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - DB_URL=mongodb://api-server-db:27017/DockerDemo
    depends_on:
      - api-server-db
